 const ActionTypes = {
    CURRENTUSER:'CURRENTUSER',
    ERROR: 'ERROR',
    SIGNUPERROR: 'SIGNUPERROR',
    SIGNIN: 'SIGNIN',
    SIGNUP: 'SIGNUP',
    GETUSERNAME: 'GETUSERNAME',
    SUBMITDATA: 'SUBMITDATA',
    GETDATA: 'GETDATA',
    GETKEYS: 'GETKEYS',
    GETBIDDERS: 'GETBIDDERS',
    GETUSERS: 'GETUSERS',
}

export default ActionTypes;
